### ISSUE TITLE
Distinguishing `CRAWLERA_DOWNLOAD_TIMEOUT` and `X-Crawlera-Timeout`

### ISSUE THREAD

**Issue by starrify** [scrapy-plugins/scrapy-crawlera#15]
Currently we have:
1. `CRAWLERA_DOWNLOAD_TIMEOUT` to specify the download timeout between a client and Crawlera nodes.
2. [`X-Crawlera-Timeout`](http://doc.scrapinghub.com/crawlera.html#x-crawlera-timeout) to specify the download timeout between Crawlera nodes and the target websites (not yet supported by this package).

Looks like they are somehow misleading and confusing. As we may not easily change the names, shall we:
1. Add some kind of notes to explain the difference.
2. Also support `X-Crawlera-Timeout` in this package.

**Comment by eLRuLL** [comment]
but `X-Crawlera-Timeout` isn't used as a settings parameter, but only a request header, I don't see how could they be mixed up.

Also `CRAWLERA_DOWNLOAD_TIMEOUT` isn't really a necessary or important setting, as the `scrapy-crawlera` middleware handles a default [`download_timeout`](https://github.com/scrapy-plugins/scrapy-crawlera/blob/master/scrapy_crawlera.py#L20) for crawlera requests, and *offers* `CRAWLERA_DOWNLOAD_TIMEOUT` if you want to change that default, which is already being handled by the more generic `DOWNLOAD_TIMEOUT` settings attribute.

**Comment by eLRuLL** [comment]
@redapple any comments here?
