### ISSUE TITLE
how to transfer the CRAWLERA headers to the crawlspider?

### ISSUE THREAD

**Issue by aohan237** [scrapy-plugins/scrapy-crawlera#17]
i buy your CRAWLERA PLANS,but the offcial doc said dont to override the parse function,but how to transfer the CRAWLERA headers to the crawlspider

**Comment by eLRuLL** [comment]
you can always setup default headers for ALL requests on Settings with [`DEFAULT_REQUEST_HEADERS`](http://doc.scrapy.org/en/1.0/topics/settings.html#default-request-headers)

**Comment by eLRuLL** [comment]
can we close this issue? (as it is not really an issue)

**Comment by redapple** [comment]
@aohan237 , I believe the issue has been discussed in Scrapinghub helpdesk channel.
Are you ok with closing it?
