### ISSUE TITLE
Documentation is incomplete: dont_proxy vs X-Crawlera-Max-Retries

### ISSUE THREAD

**Issue by dchaplinsky** [scrapy-plugins/scrapy-crawlera#26]
Documentation says that X-Crawlera-Max-Retries can control if proxying is enabled or not.

On the other hand, in the code I can see dont_proxy request meta flag which can be used to disable proxy.

I think X-Crawlera-Max-Retries only affects the proxy server itself, as it's not mentioned in the code. Is setting it to 0 will bypass the proxy?

**Comment by eLRuLL** [comment]
hi @dchaplinsky, where is the documentation that says `X-Crawlera-Max-Retries` controls if the proxying is enabled or not?

**Comment by dchaplinsky** [comment]
![scrapy-crawlera crawlera middleware for scrapy 2016-10-29 3 -27-40](https://cloud.githubusercontent.com/assets/131186/19825863/ae1cb1a8-9d87-11e6-854f-97b8f5d5d3e4.png)

I read it as: to enable scraping through crawlera you need to add that header.

**Comment by eLRuLL** [comment]
ok, yeah that was only an example, but I agree we could explain it better.
