### ISSUE TITLE
How to install crawlera-ca.crt in Scrapy

### ISSUE THREAD

**Issue by vionemc** [scrapy-plugins/scrapy-crawlera#28]
I can't access https URLs using Scrapy+Crawlera. Crawlera provides the certificate, but how to install it?

**Comment by eLRuLL** [comment]
hi @vionemc , what's the error you are receiving? Please also share your scrapy and twisted version

**Comment by redapple** [comment]
@vionemc , scrapy does not check server certificates, so scrapy should work fine with Crawlera without additional CA certificate.
As @eLRuLL asked, can you provide more detail on the error you are getting and output of `scrapy version -v`?

**Comment by redapple** [comment]
@vionemc , with no further information from your end, I'm assuming that you resolved your issue.
Hence I'm closing this ticket.
Feel free to reopen it but please provide more information (as requested previously).

**Comment by LuckyLion777** [comment]
@redapple, I used crawlera service in my Scrapy project and when I started crawl, I got 407 response error. I guess this is because crawlera-ca.cert file.
I downloaded this file and don't know how to use it.
Please help me.

**Comment by redapple** [comment]
@LuckyLion777 , an HTTP 407 error means that Scrapy does not send Crawlera credentials in the HTTP request headers. This has nothing to do with Crawlera's Certificate Authority cert file.
You need to check your scrapy-crawlera settings, namely `CRAWLERA_ENABLED = True` and `CRAWLERA_APIKEY = 'yourapikey'`

**Comment by amralaaalex** [comment]
I am facing the same issue here, in crawlera they wrote:
To fetch HTTPS pages you will need to download and install the following certificate in your HTTP client or disable SSL certificate verification:
======
I am getting timeout error when I try to fetch https pages, but it works fine if I disabled cralwera or when I use crawlera to fetch http pages
I do not know how to disable SSL certificate verification?!
