### ISSUE TITLE
use crawlera error

### ISSUE THREAD

**Issue by ichenfujun** [scrapy-plugins/scrapy-crawlera#31]
http://proxy.crawlera.com:8010?noconnect (user:

**Comment by redapple** [comment]
@ichenfujun , can you provide more information on the error?

**Comment by ichenfujun** [comment]
INFO:Using crawlera at http://proxy.crawlera.com:8010?noconnect (user: fe84844...)     only this line
my settings.py:
DOWNLOADER_MIDDLEWARES = {
                  'scrapy_crawlera.CrawleraMiddleware': 300,
     }
 50 CRAWLERA_ENABLED = True
 51 CRAWLERA_APIKEY = 'fe8484409712441f84442c14cbcdc3f9'

**Comment by redapple** [comment]
@ichenfujun , what kind of error are you having? is it a python error? or some error code from Crawlera?
It may be more suited for Crawlera support, not scrapy-crawlera middleware. Have you contacted them?

**Comment by redapple** [comment]
@ichenfujun , with no updates from you, I'm assuming that you resolved your issue.
Feel free to reopen the issue with more details.
