### ISSUE TITLE
Custom geo location

### ISSUE THREAD

**Issue by vimagick** [scrapy-plugins/scrapy-crawlera#38]
Some websites return different contents based on geo location.
Is it possible to use country codes as parameter in headers?
It tells crawlera which proxies to choose from shared pool.

```
X-Crawlera-Country: US,UK,CA
```

**Comment by eLRuLL** [comment]
Hi @vimagick you'll have to ask this on [crawlera support](https://support.scrapinghub.com/forums/1-general/categories/3-crawlera/topics/).

As I understand you can ask them to give you several crawlera users separated by region but only with non-basic plans.

If crawlera adds this as configurable settings, we'll include it ASAP on this middleware.
