### ISSUE TITLE
Automate Crawlera certificate setup

### ISSUE THREAD

**Issue by pablohoffman** [scrapy-plugins/scrapy-crawlera#41]
I've heard many Crawlera users complaining about installing the certificate (to make https work with Crawlera) and I was thinking that, since the Crawlera middleware is meant to make things easier on the client side, it could automatically download and install the certificate if it's not present, to reduce another step in the "crawlera setup process". Installing the certificate is not a major task, but also not a trivial one, and it varies per platform. But most importantly, it can be automated in things like the Crawlera middleware.

**Comment by redapple** [comment]
By default, scrapy does not check remote server certificates. So I dont
think installing Crawlera's certificate is needed with scrapy-crawlera.
Another thing, I believe scrapy-crawlera still use the http:// proxy
without CONNECT (which should be changed eventually)

**Comment by pablohoffman** [comment]
good point @redapple, no need for this ticket then.
