### ISSUE TITLE
Scrapy-crawlera breaks SplashRequest

### ISSUE THREAD

**Issue by eusid** [scrapy-plugins/scrapy-crawlera#45]
If you are using Splash and crawlera middleware the splash requests will not work. I have not tracked the requests but I assume that its trying to access my local host through the proxy.

**Comment by deti** [comment]
Hi @eusid 

Thank you for notice! We already aware about it and put this issue into our roadmap. However I'm couldn't provide any ETA for the fix arrival.

**Comment by eusid** [comment]
No problem. I'd be interested in doing the pull request with a little guidance from more experienced scrapy devs.

**Comment by deti** [comment]
Sure @eusid Feel free to PR. We would be happy to guide you there!

**Comment by eLRuLL** [comment]
@eusid if you are interested in following this problem, could you share a code example so we can see where is the problem? Splash works with Crawlera, but of course it needs some extra configuration, as you can see here: https://github.com/scrapy-plugins/scrapy-splash/issues/97

**Comment by hcoura** [comment]
Closing this since no updates, feel free to reopen if a example ever comes around.
