### ISSUE TITLE
[question] using scrapy-crawlera and scrapy imagesPipeline

### ISSUE THREAD

**Issue by hugocar** [scrapy-plugins/scrapy-crawlera#47]
Hi,
Thank you for the awesome plugin.

I m using scrapy-crawlera the way described in the documentation.
I m also using the imagesPipeline described here [doc.scrapy.org/...](https://doc.scrapy.org/en/latest/topics/media-pipeline.html)

Do the calls from the imagesPipeline go through Crawlera ?

**Comment by redapple** [comment]
Hello @hugocar , sorry for the late reply.
`ImagesPipeline` eventually calls `self.crawler.engine.download` with the generated requests for images URLs. So yes, the requests go through downloader middlewares, such as `CrawleraMiddleware`.
Are you seeing something different?

**Comment by hugocar** [comment]
Hi @redapple
Thank you for the answer.

> Are you seeing something different?

I launched my crawler and it worked just as you predicted, thanks

**Comment by redapple** [comment]
Perfect! Thanks for using Scrapy and Crawlera.
