### ISSUE TITLE
fetch https pages using scrapy + crawlera

### ISSUE THREAD

**Issue by amralaaalex** [scrapy-plugins/scrapy-crawlera#56]
in crawlera they wrote:
To fetch HTTPS pages you will need to download and install the following certificate in your HTTP client or disable SSL certificate verification:
I am getting timeout error when I try to fetch https pages, but it works fine if I disable cralwera or when I use crawlera to fetch http pages
I do not know how to disable SSL certificate verification or how to install cralwera https certificate, I have downloaded cralwera https certificate, double clicked on it, followed the wizard but nothing changed

**Comment by UnitedColorsOfNerd** [comment]
I have the same issue. works fine with http pages but any https page is timing out.

**Comment by tcurvelo** [comment]
Is this a problem yet? I can't reproduce the error with `scrapy-crawlera`. I've tried the spider below::

```
# -*- coding: utf-8 -*-
import json
import os
import scrapy


class HttpbinSpider(scrapy.Spider):
    name = 'httpbin'
    allowed_domains = ['httpbin.org']
    start_urls = ['https://httpbin.org/headers']
    crawlera_enabled = True
    crawlera_apikey = os.getenv('CRAWLERA_APIKEY')
    custom_settings = {
        'DOWNLOADER_MIDDLEWARES': {'scrapy_crawlera.CrawleraMiddleware': 610}
    }

    def parse(self, response):
        return json.loads(response.text)
```

**Comment by eLRuLL** [comment]
@amralaaalex could you please clarify if this is still a problem for you? If not we'll be closing this issue on the following days. Kind Regards.

**Comment by hcoura** [comment]
It seems this isn't a issue anymore. Closing it, feel free to reopen with problem clarification.
