### ISSUE TITLE
Ignores DOWNLOAD_TIMEOUT setting

### ISSUE THREAD

**Issue by hcoura** [scrapy-plugins/scrapy-crawlera#57]
scrapy crawlera only looks for CRAWLERA_DOWNLOAD_TIMEOUT and ignores the default way of setting timeouts in scrapy through [DownloadTimeoutMiddleware](https://doc.scrapy.org/en/latest/topics/downloader-middleware.html#scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware)

**Comment by Gallaecio** [comment]
I believe this is on purpose, and [recognized in the documentation](https://scrapy-crawlera.readthedocs.io/en/latest/settings.html#crawlera-download-timeout).

**Comment by hcoura** [comment]
@Gallaecio yeah, but it could be a bit smarter in case DOWNLOAD_TIMEOUT is bigger than it's default value when CRAWLERA_DOWNLOAD_TIMEOUT is unset.

Not sure if needed or anything, just something I run into one day and wanted to look at it later on and never got to it.
