### ISSUE TITLE
Spider crawlera_enabled argument priority

### ISSUE THREAD

**Issue by edorofeev** [scrapy-plugins/scrapy-crawlera#83]
I just want to understand, is it expectable behavior or not :)

https://github.com/scrapy-plugins/scrapy-crawlera/blob/c416d65cff762f6cbf372a99e5e6d81cddf01a4d/scrapy_crawlera/middleware.py#L141

```
return(
    getattr(spider, 'crawlera_enabled', False) or
    getattr(spider, 'use_hubproxy', False) or
    self.crawler.settings.getbool("CRAWLERA_ENABLED") or
    self.crawler.settings.getbool("HUBPROXY_ENABLED")
    )
```

This construction will return True if anyone will be True. But in this case, if we have `CRAWLERA_ENABLED = True` in settings.py, but `crawlera_enabled = False` as spider argument - crawlera will be enabled.
In my opinion, it's a little bit confused. I think spider argument should have more priority than `crawler.settings`.
Like here: https://github.com/scrapy-plugins/scrapy-crawlera/blob/master/scrapy_crawlera/middleware.py#L120

**Comment by hcoura** [comment]
I agree with you, spider setting should override the project wide settings
